# PostgreSQL. Versions 8.2 and up are supported.
default: &default
  adapter:  postgresql
  host:     postgres
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  encoding: unicode
  pool:     5
  template: template0

development:
  <<: *default
  database: escalade-rails_development

test:
  <<: *default
  database: escalade-rails_test

production:
  <<: *default
  database: escalade-rails_production
