source 'https://rubygems.org'

ruby '2.3.0'

gem 'rails', '4.2.5.1'

gem 'bootstrap-sass'
gem 'coffee-rails', '~> 4.1.0'
gem 'devise'
gem 'haml-rails'
gem 'high_voltage'
gem 'jbuilder', '~> 2.0'
gem 'jekyll'
gem 'jquery-rails'
gem 'pg'
gem 'puma'
gem 'rugged'
gem 'sass-rails', '~> 5.0'
gem 'sidekiq'
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'better_errors'
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'web-console', '~> 2.0'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end

group :development, :test do
  gem 'byebug'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rspec-rails'
end
